export const Types = {
  GET_HOME_LIST: "GET_HOME_LIST",
  GET_EDIT_HOME: "GET_EDIT_HOME",
  ADD_HOME: "ADD_HOME",
  OPEN_ADD_HOME_MODAL: "OPEN_ADD_HOME_MODAL",
  EDIT_HOME: "EDIT_HOME",
  HOME_LIST_LOADING: "HOME_LIST_LOADING",
  DELETE_HOME:"DELETE_HOME",
};
