export const Types = {
  GET_INVOICE_LIST: "GET_INVOICE_LIST",
  GET_EDIT_INVOICE: "GET_EDIT_INVOICE",
  ADD_INVOICE: "ADD_INVOICE",
  OPEN_ADD_INVOICE_MODAL:"OPEN_ADD_INVOICE_MODAL",
  EDIT_INVOICE:"EDIT_INVOICE",
  INVOICE_LIST_LOADING:"INVOICE_LIST_LOADING",
};