export const Types = {
  GET_LEAD_LIST: "GET_LEAD_LIST",
  GET_EDIT_LEAD: "GET_EDIT_LEAD",
  ADD_LEAD: "ADD_LEAD",
  OPEN_ADD_LEAD_MODAL: "OPEN_ADD_LEAD_MODAL",
  EDIT_LEAD: "EDIT_LEAD",
  LEAD_LIST_LOADING: "LEAD_LIST_LOADING",
};
