export const Types = {
  GET_RESIDENT_LIST: "GET_RESIDENT_LIST",
  GET_EDIT_RESIDENT: "GET_EDIT_RESIDENT",
  ADD_RESIDENT: "ADD_RESIDENT",
  OPEN_ADD_RESIDENT_MODAL:"OPEN_ADD_RESIDENT_MODAL",
  EDIT_RESIDENT:"EDIT_RESIDENT"
};