export const Types = {
  GET_ROOM_LIST: "GET_ROOM_LIST",
  GET_EDIT_ROOM: "GET_EDIT_ROOM",
  ADD_ROOM: "ADD_ROOM",
  OPEN_ADD_ROOM_MODAL: "OPEN_ADD_ROOM_MODAL",
  EDIT_ROOM: "EDIT_ROOM",
  CLONE_ROOM: "CLONE_ROOM",
  DELETE_ROOM: "DELETE_ROOM",
  ROOM_LIST_LOADING: "ROOM_LIST_LOADING",
};