export const Types = {
  GET_STAFF_LIST: "GET_STAFF_LIST",
  GET_EDIT_STAFF: "GET_EDIT_STAFF",
  ADD_STAFF: "ADD_STAFF",
  OPEN_ADD_STAFF_MODAL:"OPEN_ADD_STAFF_MODAL",
  EDIT_STAFF:"EDIT_STAFF",
  STAFF_LIST_LOADING:"STAFF_LIST_LOADING"
};